### PR TITLE
Add node-fetch dependency

### PR DESCRIPTION
**Pull request by iamonuwa**

### CODE REVIEW

**Review by troggy — CHANGES_REQUESTED** [review]
node-fetch is not actually used in the code. Please test your code before submitting PRs 🙏

**Comment by iamonuwa** [comment]
> node-fetch is not actually used in the code. Please test your code before submitting PRs

`node-fetch` is needed because fetch api didn't work when deployed.

**Comment by iamonuwa** [comment]
Fixed

**Comment by troggy** [comment]
merged with [fix](https://github.com/leapdao/slack-analytics/commit/9b2602b5b34990d5ae78e7f0e2ae0d14e68b4ebe)

**Pull request merged**
